/*
 * This source file was generated by the Gradle 'init' task
 */
package railway.simulator;

import railway.simulator.model.RailwaySystem;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        RailwaySystem rs = new RailwaySystem();

        rs.readInputFile(args[0]);
        rs.simulateTravel();
    }
}
